<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function hellocoop_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_login_form') {
    $form['actions']['custom_login_button'] = [
      '#type' => 'button',
      '#value' => t('ō&nbsp;&nbsp;&nbsp;Continue with Hellō'),
      '#attributes' => [
        'class' => ['hello-btn'],
      ],
      '#weight' => 10,
    ];

    $config = \Drupal::config('hellocoop.settings');
    $apiRoute = $config->get('api_route');


    // Attach a custom JavaScript library and pass the base URL.
    $form['#attached']['library'][] = 'hellocoop/custom_login';
    $form['#attached']['drupalSettings']['hellocoop']['baseUrl'] = \Drupal::request()->getSchemeAndHttpHost() . $apiRoute;
  }
}
