name: PHPUnit Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up DDEV
    - name: Set up DDEV
      uses: ddev/github-action-setup-ddev@v1

    - name: Configure DDEV for Drupal
      run: ddev config --project-type=drupal --docroot=web --php-version=8.3 --corepack-enable --project-name=hellocoop

    # Step 3: Install DDEV Drupal Contrib add-on
    - name: Install DDEV Drupal Contrib add-on
      run: ddev add-on get ddev/ddev-drupal-contrib

    # Step 4: Install phpunit
    - name: Install DDEV Drupal Contrib add-on
      run: ddev composer require --dev phpunit/phpunit

    # Step 5: Start DDEV
    - name: Start DDEV
      run: ddev start

    # Step 6: Install composer dependencies
    - name: Symlink all root files/dirs into web.modules/custom/hellocoop
      run: ddev symlink-project

    # Step 7: Run PHPUnit tests
    - name: Run PHPUnit tests
      run: ddev phpunit
