name: PHPUnit Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up DDEV
    - name: Set up DDEV
      uses: ddev/github-action-setup-ddev@v1

    # Step 3: Start DDEV
    - name: Start DDEV
      run: ddev start

    # Step 4: Install composer dependencies
    - name: Install dependencies
      run: ddev composer install

    # Step 5: Set up Drupal environment
    - name: Set up Drupal
      run: |
        ddev drush si --yes \
          --db-url=mysql://db:db@db/db \
          --site-name="Test Site"

    # Step 6: Run PHPUnit tests
    - name: Run PHPUnit tests
      run: ddev phpunit
